apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    argocd/app-name: ${{ values.name }}-dev
    grafana/dashboard-selector: service=${{ values.name }}
  tags:
    - recommended-path
    - service
    - kubernetes
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: platform-services
